export function captureException(error: Error) {
  console.info(`No yet defined...`);
  return console.error(`Caught exception: ${JSON.stringify(error)}`);
}
